# Etiquetas genéricas del sitio

title_site: fetenWork
group_name: CristobalTM
team_name: microFrameWork PHP + POO + MVC

# Menú

menu: Menu
index: Home
crud_examples: CRUD examples
users: Users
urls: Links
others_webs: Resources
github: Github
color_palette: Color palette
fontawesome: Icons by fontawesome.io
glyphicons: Iconos by Glyphicons
mvc_site: PHP + POO + MVC example

# Mensajes de confirmación

confirm_delete: Do you want to delete this record?

# Mensajes de error

error_default: Unexpected error
error_404: Wrong page

# Acciones

send: Send
delete: Delete
edit: Edit
close: Close
go_up: Go up

# Sección usuarios

name: Name
surname: Surname
email: Email
pass: Pass
add_user: Add user

# Sección enlaces

label: Label
link: Link
add_link: Add link
edit_link: Edit link

# Política de cookies

cookie_polity: This website uses cookies to offer a better user experience. If you continue browsing we consider that you accept its use.
more_information: More information
privacy_politic: Privacy politic

# Ejemplos

section_title: Home example
link_1: CSS style
link_2: Broken link
link_3: Color palette
section_1: Calendar
board_1: Day 1
board_2: Day 2
board_3: Day 3
section_2: Files
subsection_1: Text
subsection_2: Code
subsection_3: Excel
subsection_4: PDF
subsection_5: Image
calendar: See calendar
total: Read more