# Etiquetas genéricas del sitio

title_site: fetenWork
group_name: CristobalTM
team_name: microFrameWork PHP + POO + MVC

# Menú

menu: Menú
index: Inicio
crud_examples: Ejemplos A/B/M
users: Usuarios
urls: Enlaces
others_webs: Recursos
github: Github
color_palette: Paleta de colores
fontawesome: Iconos en fontawesome.io
glyphicons: Iconos en Glyphicons
mvc_site: Ejemplo PHP + POO + MVC

# Mensajes de confirmación

confirm_delete: ¿Deseas eliminar este registro?

# Mensajes de error

error_default: Ocurrió un error inesperado
error_404: La página que solicita no existe
back: Volver

# Acciones

send: Enviar
add: Agregar
delete: Borrar
edit: Editar
close: Cerrar
go_up: Subir

# Sección usuarios

name: Nombre
surname: Apellido
email: Email
pass: Contraseña
add_user: Añadir usuario
description: Descripción

# Sección enlaces

label: Etiqueta
link: Dirección
add_link: Añadir enlace
edit_link: Editar enlace

# Política de cookies

cookie_polity: Esta web utiliza cookies para ofrecer una mejor experiencia de usuario. Si continúas navegando consideramos que aceptas su uso.
more_information: Más información
privacy_politic: Política de privacidad

# Ejemplo portada

section_title: Ejemplo de portada
link_1: Estilo CSS
link_2: Enlace roto
link_3: Paleta de colores
section_1: Calendario
board_1: Día 1
board_2: Día 2
board_3: Día 3
section_2: Documentos
subsection_1: Texto
subsection_2: Código
subsection_3: Excel
subsection_4: PDF
subsection_5: Imagen
calendar: Ver calendario
total: Ver más