##  Archivo de configuración

# Controlador por defecto
DEFAULT_CONTROLLER: Usuarios
    
# Acción por defecto
DEFAULT_ACTION: index

# Ruta de los modelos
PATH_MODEL: model/

# email del administrador
ADMIN_EMAIL: cristobaltm@gmail.com
