#############################
## CONFIGURACIÓN DEL SITIO ##
#############################

# Título del sitio
TITLE_SITE: Ejemplo PHP MySQLi POO MVC

# email del administrador
ADMIN_EMAIL: cristobaltm@gmail.com

# Nombre del autor
AUTHOR_NAME: Cristobal TM

# Web del autor
AUTHOR_WEB: https://github.com/cristobaltm/mvc


#########################
## VALORES POR DEFECTO ##
#########################

# Controlador por defecto
# (también será el nombre por defecto para modelo y vista)
DEFAULT_CONTROLLER: Usuarios

# Acción por defecto
DEFAULT_ACTION: index

# Plantilla por defecto
DEFAULT_TEMPLATE: index

# Entorno por defecto
DEFAULT_ENVIRONMENT: dev

# Nombre de la variable GET que define el controlador
GET_CONTROLLER: controller

# Nombre de la variable GET que define la acción
GET_ACTION: action


###########
## RUTAS ##
###########

# Ruta de los modelos
PATH_MODELS: model/

# Ruta de las vistas
PATH_VIEWS: view/

# Ruta de los controladores
PATH_CONTROLLERS: controller/

# Ruta de los archivos web
PATH_WEB: web/

